# Generated by Django 3.2 on 2021-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmodel', '0004_auto_20210511_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
