# Generated by Django 3.2 on 2021-05-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmodel', '0006_remove_schedule_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='scheduletime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
