# Generated by Django 3.2 on 2021-05-17 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskmodel', '0007_alter_schedule_scheduletime'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='scheduledate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='scheduletime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
