# Generated by Django 3.2 on 2021-05-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmodel', '0008_auto_20210517_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='userid',
        ),
        migrations.AddField(
            model_name='note',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
